language:
- objective-c
- c++

compiler:
- clang

sudo: false
os: osx

matrix:
  include:
    - osx_image: xcode9.4
      env: CONFIG=Debug
    - osx_image: xcode9.4
      env: CONFIG=Release
    - osx_image: xcode10.1
      env: CONFIG=Debug
    - osx_image: xcode10.1
      env: CONFIG=Release

script:
- mkdir build
- cd build
- cmake -G Xcode ..
- cmake --build . --config ${CONFIG} | sed 's/-Wl,-.*//g'
- ctest -C ${CONFIG} . -V
- cd ..
- PACKAGE_NAME=`echo $TRAVIS_REPO_SLUG | sed 's/.*\///g'`
- PACKAGE_REV=`echo $TRAVIS_COMMIT | sed -e 's/^[[:alnum:]]\{7\}/&-/g' | sed 's/-.*//'`
- mkdir $PACKAGE_NAME
- if [ -e package-info.json ]; then cp package-info.json $PACKAGE_NAME; fi
- for f in *.md; do [ -e "$f" ] && cp "$f" $PACKAGE_NAME ; done
- if [ -e icon.png ]; then cp icon.png $PACKAGE_NAME; fi
- if [ -e CMakeLists.txt ]; then cp CMakeLists.txt $PACKAGE_NAME; fi
- if [ -d code ]; then cp -r code $PACKAGE_NAME; fi
- if [ -d docs ]; then cp -r docs $PACKAGE_NAME; fi
- if [ -d examples ]; then cp -r examples $PACKAGE_NAME; fi
- if [ -d extensions ]; then cp -r extensions $PACKAGE_NAME; fi
- if [ -d externals ]; then cp -r externals $PACKAGE_NAME; fi
- if [ -d extras ]; then cp -r extras $PACKAGE_NAME; fi
- if [ -d help ]; then cp -r help $PACKAGE_NAME; fi
- if [ -d init ]; then cp -r init $PACKAGE_NAME; fi
- if [ -d java-classes ]; then cp -r java-classes $PACKAGE_NAME; fi
- if [ -d java-doc ]; then cp -r java-doc $PACKAGE_NAME; fi
- if [ -d javascript ]; then cp -r javascript $PACKAGE_NAME; fi
- if [ -d jsui ]; then cp -r jsui $PACKAGE_NAME; fi
- if [ -d media ]; then cp -r media $PACKAGE_NAME; fi
- if [ -d misc ]; then cp -r misc $PACKAGE_NAME; fi
- if [ -d patchers ]; then cp -r patchers $PACKAGE_NAME; fi
- if [ -d support ]; then cp -r support $PACKAGE_NAME; fi
- if [ -d source ]; then cp -r source $PACKAGE_NAME; fi
- if [ -d tests ]; then cp -r tests $PACKAGE_NAME; fi
- if [ -e $PACKAGE_NAME/ReadMe-Public.md ]; then rm -f $PACKAGE_NAME/ReadMe.md; mv $PACKAGE_NAME/ReadMe-Public.md $PACKAGE_NAME/ReadMe.md; fi
- mkdir dist
- CONFIG_LOWERCASE=`echo $CONFIG | tr '[A-Z]' '[a-z]'`
- zip -r dist/$PACKAGE_NAME-mac-$PACKAGE_REV-$CONFIG_LOWERCASE.zip $PACKAGE_NAME

deploy:
  provider: s3
  access_key_id: AKIAJ4NHY5NBHT76DRGA
  secret_access_key:
    secure: "qjpFRGnUoivaWGQWZBYrgoG92N+qYL/SjNwQIfatMGFzKsso7TS33lqljIrVTh9WSOoLBRV5p9m+480ezrC/JvDtVGB9D6WDcG9QMfTEhLbZ4l6ege2C0waYSABhNChOgl7VgbmVX8V+J3r4THxGLBWmnjX4c8bUIwaY4iL8q+8EaMzswx+1ONkTfzMb1DFSP3dAUA3MkAYhLuh9kxZY0vW8FecoA5MlT/9iIfbmsBPbqsxx+HywtA0ktapTVb3DBUyo110QcaGgDyQ48LURp09n1jlo6nVO4f5VfO0durEsQ2Sv2QewtRvcGH7le3R8NwdvYmsEIi/s/hXYHmDB1dz+XPSG286ZOW3QjVts5fbrxzNhXvpr5g7d+J9aUP0MBbbNKjScFJacpRiL8QYZjtYexL7MiksQlJkURY/u6TYLPTcoDJxN2xY2rQp04aQioX/pYzcDlyAV2vItjyKmelkscrwZBuWaurX08iCvGGJKXd7Tx7hmQp46vmQbM8wxx+BUK/+if6eb7c2rMXlTUtTiRndgX6AzW7dQtX31qX+hfjINhgZ+NGJ2kM3gIgyyJEDDQZYjCkAW6Kh/smCen+t+FZehk/jquXPlubw82DVTJNHMY27yI3gpWnKLCwZoBPwjX23q1S0CtZKXP6BEZsKeYHwLkJJtpj4SWFEVUcA="
  bucket: cycling74-ci-public
  region: us-west-1
  skip_cleanup: true
  local-dir: dist
  upload-dir: $PACKAGE_NAME
  acl: public_read
  on:
    repo: Cycling74/$PACKAGE_NAME
    all_branches: true
